name: forcar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  built_collection: 5.1.1
  built_value: ^8.4.4
  cached_network_image: ^3.2.3
  calendar_date_picker2: ^0.4.5
  cloud_firestore: ^4.4.4
  cloud_firestore_platform_interface: ^5.11.4
  cloud_firestore_web: ^3.3.4
  cloud_functions: ^4.0.12
  cloud_functions_platform_interface: ^5.1.31
  cloud_functions_web: ^4.3.20
  collection: 1.16.0
  easy_debounce: ^2.0.3
  excel: ^2.0.1
  expandable: 5.0.1
  file_picker: ^5.2.6
  firebase_auth: ^4.2.9
  firebase_auth_platform_interface: ^6.11.11
  firebase_auth_web: ^5.2.8
  firebase_core: ^2.7.0
  firebase_core_platform_interface: ^4.5.3
  firebase_core_web: ^2.2.1
  firebase_messaging: ^14.2.6
  firebase_messaging_platform_interface: ^4.2.15
  firebase_messaging_web: ^3.2.16
  firebase_storage: ^11.0.15
  firebase_storage_platform_interface: ^4.1.31
  firebase_storage_web: ^3.3.24
  fl_chart: ^0.61.0
  flutter_animate: ^4.1.0
  flutter_cache_manager: 3.3.0
  flutter_google_places: 0.3.0
  flutter_html: ^3.0.0-alpha.6
  flutter_rating_bar: 4.0.1
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  from_css_color: 2.0.0
  geolocator: ^9.0.2
  geolocator_android: ^4.1.7
  geolocator_apple: ^2.2.5
  geolocator_platform_interface: ^4.0.7
  geolocator_web: 2.1.6
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  google_maps: 6.2.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_platform_interface: ^2.2.6
  google_maps_flutter_web: ^0.4.0+7
  google_sign_in: ^6.0.2
  google_sign_in_ios: ^5.6.1
  google_sign_in_platform_interface: ^2.3.1
  google_sign_in_web: ^0.11.0+2
  image_picker: ^0.8.7
  image_picker_android: ^0.8.6+1
  image_picker_for_web: ^2.1.12
  image_picker_ios: ^0.8.7+1
  image_picker_platform_interface: ^2.6.3
  infinite_scroll_pagination: 3.2.0
  intl: 0.17.0
  json_path: ^0.4.2
  json_serializable: ^6.6.1
  mask_text_input_formatter: 2.4.0
  mime_type: 1.0.0
  page_transition: ^2.0.9
  percent_indicator: ^4.2.3
  pin_code_fields: 7.4.0
  plugin_platform_interface: ^2.1.4
  provider: 6.0.4
  rxdart: 0.27.4
  shared_preferences: ^2.0.18
  sign_in_with_apple: ^4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: ^1.0.1
  sqflite: ^2.2.6
  substring_highlight: 1.0.33
  table_calendar: ^3.0.8
  timeago: ^3.3.0
  url_launcher: ^6.1.10
  video_player: ^2.6.0
  video_player_android: ^2.4.2
  video_player_avfoundation: ^2.4.2
  video_player_platform_interface: ^6.1.0
  video_player_web: ^2.0.15


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
#  provider: 6.0.0
  rxdart: 0.27.7
#  webview_flutter_android: 2.10.3
#  webview_flutter_platform_interface: 1.9.5
#  webview_flutter_wkwebview: 2.9.5

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  flutter_launcher_icons: ^0.12.0

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Wlff
      fonts:
        - asset: assets/fonts/WLFF.ttf
    - family: Save
      fonts:
        - asset: assets/fonts/save.ttf
    - family: 4carWeb
      fonts:
        - asset: assets/fonts/4car-web.ttf
    - family: Calendar
      fonts:
        - asset: assets/fonts/calendar.ttf
    - family: IcSmallStar14x14
      fonts:
        - asset: assets/fonts/ic_small_star_14x14.ttf
    - family: Refresh
      fonts:
        - asset: assets/fonts/refresh.ttf
    - family: Edit
      fonts:
        - asset: assets/fonts/edit.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
